### PR TITLE
Hero

### PR DESCRIPTION
**Pull request by ianmah**
implement hero section

### CODE REVIEW

**Comment by luceliu** [comment]
image
are we gonna fix the hover area ? is it possible

**Comment by ianmah** [comment]
@luceliu what issue are you seeing?

**Comment by luceliu** [comment]
@ianmah kay soz that screenshot wasn't very helpful but in that screenshot my mouse isn't actually on the sign - the entire rectangle around it is an 'active hover area'

**Comment by ianmah** [comment]
I'm going to ask design. Idk what the preferred behaviour is

**Pull request merged**
