### PR TITLE
Bugfix release #2?

### PR DESCRIPTION
**Pull request by Ciuffi**
@Eric1015 fixed the take be back home button bug.

@ianmah Reworked sponsor images to fix some bugs

I changed the sponsorship urls to sponsorship@nwplus.io

Lets get this out asap!!!

### CODE REVIEW

**Comment by ianmah** [comment]
whats the staging url again ;o

**Comment by Ciuffi** [comment]
@ianmah https://staging.nwplus.io/

Sponsors look a little small don't they?

**Comment by ianmah** [comment]
@Ciuffi purposely made them small so that the difference in sizes of logos due to different aspect ratios would be less noticeable - hard to put my thinking into words but basically the smaller the logos are, the pixel area that the logos differ is less.. idk maybe I'm insane

**Comment by Ciuffi** [comment]
@ianmah I definitely see what you mean, just seems really small to me

**Comment by Ciuffi** [comment]
@jvssicawu any comments?

**Comment by kozr** [comment]
Groundswell and RBC logo translate to the right when hovered over.

**Comment by ianmah** [comment]
I made a small change that hopefully fixes the hover / translate bug

Looks like this is where travis auto deploys to https://nwhacks-2019.firebaseapp.com/ and my fix seems to be working, but it hasn't deployed to staging.nwplus.io yet

**Pull request merged**
