### PR TITLE
Small navbar fixes request by design

### PR DESCRIPTION
**Pull request by Ciuffi**
I decided that the navbar appearing/disappearing on scroll feels the most natural.

I also changed the nwHacks logo to scroll back to the top.

### CODE REVIEW

**Comment by kozr** [comment]
Before 
image
After

image

**Comment by ianmah** [comment]
@kozr already fixed by @Ciuffi https://github.com/nwplus/nwhacks2020/commit/644130446ab5e3f9c06c107c4f4c830eba4a257b

**Comment by luceliu** [comment]
wait no navbar for mobile?

**Comment by Ciuffi** [comment]
@luceliu no mobile navbar on the figma

Should be good to go now

**Pull request merged**
