### PR TITLE
Outer signup styling

### PR DESCRIPTION
**Pull request by Ciuffi**
This includes the outer styling like the bread crumbs, navbar, and buttons.

It also includes per page validations. Please make sure it works.

The best way to test this is: (Make sure to use a real email in the email field)

- For each page, fill out all fields but one and try to submit. 
	- if it fails, thats good. 
- Then fill out the last field and make sure you can move onto the next page.
- Continue until you submit the application.
- Check your email to make sure you've received an email confirmation (may take up to 5 minutes)

### CODE REVIEW

**Comment by Ciuffi** [comment]
Things that still need to be fixed:
Breadcrumbs on mobile
Button placement on mobile
Name section on mobile
A final "Thanks for submitting" page.

**Comment by Ciuffi** [comment]
@AustinKobayashi  @ianmah  @kozr @luceliu @StanfordLin @Eric1015 @jvssicawu Okay all of those above problems have been fixed.

to test: Just go through the form and follow the instructions above. Please try to test especially on mobile. I've put up a staging site so you can test it here: https://nwhacks-2019.firebaseapp.com/

Once this goes through, we can start a merge into master and release. I think everything is ready to go. If there are any HUGE bugs, let me know asap and I'll fix them before. For smaller bugs, i'll leave them to the next week so we can release on time(ish).

Thanks for the great work everyone! Special thanks to @ianmah, @luceliu and @AustinKobayashi for their last minute crunching and PR reviewing yesterday.

**Comment by StanfordLin** [comment]
When I zoom out on mobile, there's white space, tried on Brave (chromium) and Chrome browser

Screenshot_20191117-112537
Screenshot_20191117-112548
Screenshot_20191117-112626
Screenshot_20191117-112815

**Comment by AustinKobayashi** [comment]
Noticed that on mobile, the "There are some errors on the page" message is too long. It causes the page to become horizontally scrollable. This was on chrome for android

76197631_463406077714081_8282110489144590336_n

75636066_804879346611435_5483905597487185920_n

**Comment by Ciuffi** [comment]
@AustinKobayashi @StanfordLin I think I've fixed horizontal scrolling, take a look.

**Pull request merged**
