### PR TITLE
The video player section

### PR DESCRIPTION
**Pull request by Ciuffi**
Click on the play button to see the video.

I'm not sure if we want the player to be closable.

@jvssicawu what do you think? Should there be an X to close the video? If so could you make up a quick design?

The play buttons match btw!

image

image

### CODE REVIEW

**Comment by ianmah** [comment]
Seeing weird blue bar

Chrome, Mac, 1920x1080

Also I feel like it should close. If not on an ❌clicking outside of the video?
Screen Shot 2019-10-10 at 8 26 23 PM

**Comment by Ciuffi** [comment]
@ianmah Should have fixed the blue bar issue. LMK if its still there.

**Comment by jvssicawu** [comment]
I created a close button on Figma, but I think what Ian said about clicking outside the video is the most intuitive way for the video to transition back. Or once the video ends, automatically have it transition back. We can implement the close button just to have an extra visual cue though.

**Comment by luceliu** [comment]
@Ciuffi can you make the video the same size as or smaller than device viewport? right now the video's height is slightly larger than the height of my screen which seems awkward

**Comment by Ciuffi** [comment]
@luceliu Could you check the viewport thing again? I made it a better size

**Comment by Ciuffi** [comment]
fixes #6

**Pull request merged**
